### ISSUE TITLE
Issue with Glib library

### ISSUE THREAD

**Issue by alfal85** [fomy/destor#3]
Thank you for sharing the Destor platform publicly. I'm trying to use Destor for my research in deduplication and I have a small problem related to the glib directory. I installed libglib3-dev but I am still having an error when trying to run the configuration file. I copied the header file to /usr/local/include with no luck.

Could you please tell me what should I do to fix this.

Thanks

**Comment by sktzwhj** [comment]
I would suggest you not to use apt-get to install the glib. Install the version mentioned in the doc from source code works for me.

**Comment by alfal85** [comment]
Great, that solved the issue
Thanks for your help
