### ISSUE TITLE
Working crypto library not found

### ISSUE THREAD

**Issue by NJUKang** [fomy/destor#5]
When run the configure file, I get an error like this……

checking for SHA_Update in -lcrypto... no
configure: error: *** Working crypto library not found ***

I am sure that  I had installed the libssl-dev

**Comment by NJUKang** [comment]
I fix the error by modify the configure file.
This error occured, beacause the  latest libssl havn't the SHA-Update() function, but have SHA1-Update().

**Comment by raindeavor** [comment]
@NJUKang  Hello,I also got an error like this,so how to solve this problem?(Editting configure file,and replace all "SHA_Update" with "SHA1_Update?")

**Comment by NJUKang** [comment]
> @NJUKang Hello,I also got an error like this,so how to solve this problem?(Editting configure file,and replace all "SHA_Update" with "SHA1_Update?")

I only changed two "SHA_Update" in line 4064 and 4068.
or you can modify the "configure.ac" and replace the only one "SHA_Update" with "SHA1_Update" in this file. 
but you need to create a new configure by autoconf.
I think the first method is easier for me.

**Comment by raindeavor** [comment]
I tried the second yesterday,it worked.
Listening to me，thank u!  Because of u......

**Comment by LongTengYiFei** [comment]
I change the 4064 and 4068, but I then get "Working glib.h header not found".

**Comment by LongTengYiFei** [comment]
Shouldn't we install an older crypto lib? The newest lib has SHA1_Update, but the source code of destor has SHA_Update.
