### ISSUE TITLE
multiple definition

### ISSUE THREAD

**Issue by LongTengYiFei** [fomy/destor#7]
gcc  -g -O0 -Wall   -o destor  src/libdestor.a src/index/libindex.a src/storage/libstorage.a src/utils/libutils.a src/recipe/librecipe.a src/chunking/libchunk.a src/fsl/libfsl.a -lpthread -lcrypto -lglib 
/usr/bin/ld: src/libdestor.a(jcr.o):/home/cyf/destor/src/destor.h:281: multiple definition of `destor'; src/libdestor.a(destor.o):/home/cyf/destor/src/destor.h:281: first defined here
/usr/bin/ld: src/libdestor.a(config.o):/home/cyf/destor/src/destor.h:281: multiple definition of `destor'; src/libdestor.a(destor.o):/home/cyf/destor/src/destor.h:281: first defined here
/usr/bin/ld: src/libdestor.a(do_backup.o):/home/cyf/destor/src/destor.h:281: multiple definition of `destor'; src/libdestor.a(destor.o):/home/cyf/destor/src/destor.h:281: first defined here
/usr/bin/ld: src/libdestor.a(read_phase.o):/home/cyf/destor/src/destor.h:281: multiple definition of `destor'; src/libdestor.a(destor.o):/home/cyf/destor/src/destor.h:281: first defined here
/usr/bin/ld: src/libdestor.a(read_phase.o):/home/cyf/destor/src/backup.h:60: multiple definition of `read_queue'; src/libdestor.a(do_backup.o):/home/cyf/destor/src/backup.h:60: first defined here
/usr/bin/ld: src/libdestor.a(read_phase.o):/home/cyf/destor/src/backup.h:62: multiple definition of `chunk_queue'; src/libdestor.a(do_backup.o):/home/cyf/destor/src/backup.h:62: first defined here
/usr/bin/ld: src/libdestor.a(read_phase.o):/home/cyf/destor/src/backup.h:64: multiple definition of `hash_queue'; src/libdestor.a(do_backup.o):/home/cyf/destor/src/backup.h:64: first defined here
/usr/bin/ld: src/libdestor.a(read_phase.o):/home/cyf/destor/src/backup.h:66: multiple definition of `trace_queue'; src/libdestor.a(do_backup.o):/home/cyf/destor/src/backup.h:66: first defined here
/usr/bin/ld: src/libdestor.a(read_phase.o):/home/cyf/destor/src/backup.h:68: multiple definition of `dedup_queue'; src/libdestor.a(do_backup.o):/home/cyf/destor/src/backup.h:68: first defined here
/usr/bin/ld: src/libdestor.a(read_phase.o):/home/cyf/destor/src/backup.h:70: multiple definition of `rewrite_queue'; src/libdestor.a(do_backup.o):/home/cyf/destor/src/backup.h:70: first defined here
/usr/bin/ld: src/libdestor.a(chunk_phase.o):/home/cyf/destor/src/destor.h:281: multiple definition of `destor'; src/libdestor.a(destor.o):/home/cyf/destor/src/destor.h:281: first defined here
......

**Comment by NJUKang** [comment]
I fixed this problem in my repository, hopefully that helps!
Here is the [link](https://github.com/NJUKang/destor).

**Comment by LongTengYiFei** [comment]
In configure.ac, change the CFLAGS="-g -O2 -Wall" in to CFLAGS="-g -O2 -Wall -fcommon".
